vse:
  docker: &ref_0
    - image: 'circleci/node:8.11.3'
version: 2.1
jobs:
  build:
    docker: *ref_0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm build
      - persist_to_workspace: null
        root: .
        paths:
          - .
  deploy:
    docker: *ref_0
    steps:
      - attach_workspace: null
        at: .
      - run: null
        command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy: null
        requires:
          - build
        filters:
          branches:
            only: main
